name: C/C++ CI

on:
  push:
    brances:
      - master
      - develop

    paths:
      - 'src/**'
      - 'include/**'
      - '.github/workflows/**'


jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify start to gitlama
    steps:
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: |-
            ${{ github.actor }} started a build of colibri-core
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: notification
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install pkg-config autoconf-archive
             fi

      - name: Build and install Colibri-Core
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          bash bootstrap
          ./configure
          make
          sudo make install

      - name: test
        env:
          CXX: ${{ matrix.compiler }}
        run: colibri-test
        continue-on-error: true

      - name: Notify IRC of failure
        if: ${{ failure() }}
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: "Building colibri-core with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00034FAIL\u0003"

      - name: Notify IRC of success
        if: ${{ success() }}
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: "Building colibri-core with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00033SUCCESS\u0003"
