---
name: C/C++ CI

on:
  push:
    brances:
      - master
      - develop

    paths:
      - configure.ac
      - src/**
      - include/**
      - .github/workflows/**

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify start to gitlama
    steps:
      - name: IRC notification
        uses: LanguageMachines/ticcactions/irc-init@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: notification
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
             sudo apt-get install pkg-config autoconf-archive
             fi
#      - uses: LanguageMachines/ticcactions/setup-cppcheck@v1
      - uses: LanguageMachines/ticcactions/irc-nick@v1

#      - name: Static Code-check
#        if: ${{ env.action_status == '' }}
#        run: cppcheck ${{ env.cpc_opts }} .

      - uses: LanguageMachines/ticcactions/cpp-safe-build@v1

      - name: Notify IRC of build result
        uses: LanguageMachines/ticcactions/irc-status@v1
        with:
          branch: ${{ github.ref_name }}
          nickname: ${{ env.nick }}
          step: build
          status: ${{ env.action_status }}
          details: ${{ env.action_details }}

      - name: test
        id: colibrites
        env:
          CXX: ${{ matrix.compiler }}
        run: colibri-test
        continue-on-error: true

      - name: Notify IRC of end result
        uses: LanguageMachines/ticcactions/irc-status@v1
        with:
          branch: ${{ github.ref_name }}
          nickname: ${{ env.nick }}
          step: testing
          status: ${{ env.action_status }}
          details: ${{ env.action_details }}
